I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter_1.rpy", line 3416, in script call
    call lanaRjt1 from _call_lanaRjt1
  File "game/chapter_1.rpy", line 3860, in script call
    call REJECTEDLAW from _call_REJECTEDLAW
  File "game/chapter_1.rpy", line 2296, in script
    jump part_1
ScriptError: could not find label 'part_1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter_1.rpy", line 3416, in script call
    call lanaRjt1 from _call_lanaRjt1
  File "game/chapter_1.rpy", line 3860, in script call
    call REJECTEDLAW from _call_REJECTEDLAW
  File "game/chapter_1.rpy", line 2296, in script
    jump part_1
  File "C:\Users\DESKTOP\Downloads\Programs\renpy-8.0.3-sdk\renpy\ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\DESKTOP\Downloads\Programs\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'part_1'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
 0.2
Tue May  9 09:21:54 2023
