I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\Renpy projects\\New Beginings In Japan\\game\\saves\\navigation.json.new' -> 'D:\\Renpy projects\\New Beginings In Japan\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Renpy projects\New Beginings In Japan\dialog data\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "D:\Renpy projects\New Beginings In Japan\dialog data\renpy-8.0.3-sdk\renpy\main.py", line 610, in main
    renpy.dump.dump(False)
  File "D:\Renpy projects\New Beginings In Japan\dialog data\renpy-8.0.3-sdk\renpy\dump.py", line 262, in dump
    os.rename(new, filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\Renpy projects\\New Beginings In Japan\\game\\saves\\navigation.json.new' -> 'D:\\Renpy projects\\New Beginings In Japan\\game\\saves\\navigation.json'

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
 0.3
Thu May 25 23:10:58 2023
